# Generated by Django 3.0.4 on 2020-05-05 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='questions_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
