# Generated by Django 3.0.4 on 2020-05-20 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionApp', '0002_question_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
        migrations.AlterField(
            model_name='question',
            name='collect',
            field=models.ManyToManyField(blank=True, related_name='collect_question', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
    ]
