# Generated by Django 3.0.4 on 2020-05-20 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionApp', '0003_auto_20200520_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='users_unlike',
            field=models.ManyToManyField(blank=True, related_name='questions_unlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
