# Generated by Django 3.0.4 on 2020-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分组名称')),
                ('number', models.IntegerField(unique=True, verbose_name='分组序号')),
            ],
        ),
    ]
