# Generated by Django 3.0.4 on 2020-05-10 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AnswerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='badNum',
            field=models.IntegerField(default=0, verbose_name='反对数'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='collect',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='goodNum',
            field=models.IntegerField(default=0, verbose_name='赞数'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='综合质量'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(verbose_name='评论内容')),
                ('pubDate', models.DateTimeField(auto_now=True, verbose_name='回答时间')),
                ('goodNum', models.IntegerField(default=0)),
                ('badNum', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', to='AnswerApp.AnswerModel')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
        ),
    ]
