# Generated by Django 3.0.4 on 2020-05-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerApp', '0002_auto_20200510_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answermodel',
            options={'ordering': ('-grade',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentText',
            new_name='comment_text',
        ),
    ]
