# Generated by Django 3.0.4 on 2020-05-11 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AnswerApp', '0003_auto_20200511_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='user_like_answer',
            field=models.ManyToManyField(blank=True, related_name='answers_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='user_unlike_answer',
            field=models.ManyToManyField(blank=True, related_name='answers_unlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='collect',
            field=models.ManyToManyField(related_name='collect_answer', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
    ]
